### PR TITLE
fix: change shortcu for yt embedding

### LINKED ISSUE #39: Change YouTube Embed Shortcut to Ctrl + Y for Windows
Right now, the keybaord shortcut for embeding a YouTube link is Shift + Y. But when editing content normally, the user might need to use capital Y, and would need to use Shift + Y for it, but this automatically creates the markdown text for the YouTube embed 

Because of this, we should change the command to Ctrl + Y ideally or some other letter

### PR DESCRIPTION
**Pull request by krushiraj**
- Change shortcut for embedding youtube video
- `Cmd/Ctrl + Sihft + Y` is new shortcut

Closes #39

### CODE REVIEW

**Comment by pbteja1998** [comment]
@krushiraj Please also fix #21 in this pr itself.

File: src/components/learn/Editor/lib/KeyboardShortcuts.ts [hunk 1]
```diff
@@ -122,8 +124,8 @@ export const KeyboardShortcuts = {
     if (currentType === 'YOUTUBE') {
```
Comment (pbteja1998) [inline src/components/learn/Editor/lib/KeyboardShortcuts.ts:124]: You can remove this case. We don't need to address YOUTUBE case separately anymore

Remove if case, and even for YOUTUBE, whatever happens in else should happen.
